### ISSUE TITLE
0.4.1 already released on Supermarket but there is no related tag

### ISSUE THREAD

**Issue by poliva83** [sous-chefs/reprepro#14]
@tas50 I see you have taken over this cookbook. I noticed that 0.4.1 has already been pushed to Supermarket based on content up to this commit https://github.com/tas50/reprepro/commit/e8d19c70ba355a9d4551cba55a1a4a5283e3e6b3. I suggest you tag that commit (release) with 0.4.1 now and version bump master. Hopefully you have the rights to push new versions to Supermarket in future since you took the project over.

**Comment by tas50** [comment]
0.4.1 has been tagged. Sorry for the delay in getting back to you here
